"""
CONTROLES ISO 27001:2022 - ANEXO A
Templates con ejemplos para empresa de Factoring y Confirming
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional
from enum import Enum


class TipoControl(Enum):
    PREVENTIVO = "preventivo"
    DETECTIVO = "detectivo"
    CORRECTIVO = "correctivo"


class CategoriaControl(Enum):
    A5_ORGANIZACIONAL = "A.5"
    A6_PERSONAS = "A.6"
    A7_FISICO = "A.7"
    A8_TECNOLOGICO = "A.8"
    A9_ACCESO = "A.9"
    A10_CRIPTOGRAFIA = "A.10"
    A11_OPERACIONES = "A.11"
    A12_COMUNICACIONES = "A.12"
    A13_ADQUISICION = "A.13"
    A14_PROVEEDORES = "A.14"
    A15_INCIDENTES = "A.15"
    A16_CONTINUIDAD = "A.16"
    A17_CUMPLIMIENTO = "A.17"


class EstadoControl(Enum):
    NO_APLICA = "no_aplica"
    EN_DISENO = "en_diseno"
    EN_IMPLEMENTACION = "en_implementacion"
    IMPLEMENTADO = "implementado"
    OPERATIVO = "operativo"


@dataclass
class Control:
    codigo: str
    titulo: str
    descripcion: str
    categoria: str
    tipo: str
    objetivo: str
    aplicabilidad_factoring: bool = True
    aplicabilidad_confirming: bool = True
    estado: str = "no_implementado"
    evidencia: List[str] = field(default_factory=list)
    responsable: str = ""
    ejemplo_factoring: str = ""
    ejemplo_confirming: str = ""
    normas_relacionadas: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict:
        return {
            "codigo": self.codigo,
            "titulo": self.titulo,
            "descripcion": self.descripcion,
            "categoria": self.categoria,
            "tipo": self.tipo,
            "objetivo": self.objetivo,
            "aplicabilidad_factoring": self.aplicabilidad_factoring,
            "aplicabilidad_confirming": self.aplicabilidad_confirming,
            "estado": self.estado,
            "evidencia": self.evidencia,
            "responsable": self.responsable,
            "ejemplo_factoring": self.ejemplo_factoring,
            "ejemplo_confirming": self.ejemplo_confirming,
            "normas_relacionadas": self.normas_relacionadas,
        }


class ControlesISO27001:
    @staticmethod
    def get_all() -> List[Control]:
        return [
            # A.5 Controles Organizacionales (5 controles)
            Control(
                codigo="A.5.1",
                titulo="Políticas de seguridad de la información",
                descripcion="Politicas y objetivos de seguridad definidos, aprobados y publicados",
                categoria="A.5",
                tipo="preventivo",
                objetivo="Proporcionar dirección y apoyo para la seguridad",
                ejemplo_factoring="Politica de seguridad para operaciones de factoring",
                ejemplo_confirming="Politica de seguridad para gestion de pagos a proveedores",
                responsable="CISO",
                evidencia=["Politica de seguridad", "Aprobacion de direccion"],
                normas_relacionadas=["ISO27001", "COBIT"],
            ),
            Control(
                codigo="A.5.2",
                titulo="Revisión de las políticas",
                descripcion="Revisar las politicas a intervalos planificados",
                categoria="A.5",
                tipo="preventivo",
                objetivo="Asegurar relevancia y adecuacion continua",
                ejemplo_factoring="Revision anual de politicas de factoring",
                ejemplo_confirming="Revision de politicas de confirming",
                responsable="CISO",
                evidencia=["Actas de revision", "Versiones actualizadas"],
                normas_relacionadas=[],
            ),
            Control(
                codigo="A.5.3",
                titulo="Segregación de funciones",
                descripcion="Separar responsabilidades para evitar conflictos de interes",
                categoria="A.5",
                tipo="preventivo",
                objetivo="Prevenir fraude y ошибки",
                ejemplo_factoring="Separacion entre aprobacion de factoring y registro",
                ejemplo_confirming="Separacion entre procesamiento y aprobacion de pagos",
                responsable="RRHH",
                evidencia=["Matriz de segregacion", "Descripciones de puesto"],
                normas_relacionadas=["SOX", "Basilea III"],
            ),
            Control(
                codigo="A.5.4",
                titulo="Responsabilidad de la gestión",
                descripcion="Asignar responsabilidades de seguridad",
                categoria="A.5",
                tipo="preventivo",
                objetivo="Asegurar ownership de seguridad",
                ejemplo_factoring="CISO responsable de seguridad de factoring",
                ejemplo_confirming="Responsable de seguridad en confirming",
                responsable="Direccion",
                evidencia=["Organigrama", "Actas de designacion"],
                normas_relacionadas=[],
            ),
            Control(
                codigo="A.5.5",
                titulo="Contacto con autoridades",
                descripcion="Mantener contacto con autoridades relevantes",
                categoria="A.5",
                tipo="preventivo",
                objetivo="Facilitar respuesta a incidentes",
                ejemplo_factoring="Contacto con superintendencia de bancos",
                ejemplo_confirming="Contacto con entidades regulatorias",
                responsable="CISO",
                evidencia=["Lista de contactos", "Acuerdos"],
                normas_relacionadas=["LOC", "Regulacion financiera"],
            ),
            # A.6 Controles de Personas (2 controles)
            Control(
                codigo="A.6.1",
                titulo="Selección de personal",
                descripcion="Verificar antecedentes de candidatos",
                categoria="A.6",
                tipo="preventivo",
                objetivo="Asegurar idoneidad del personal",
                ejemplo_factoring="Verificacion de antecedentes para analistas de factoring",
                ejemplo_confirming="Verificacion para personal de pagos",
                responsable="RRHH",
                evidencia=["Politica de seleccion", "Registros de verificacion"],
                normas_relacionadas=["GDPR"],
            ),
            Control(
                codigo="A.6.2",
                titulo="Términos de empleo",
                descripcion="Incluir requisitos de seguridad en contratos",
                categoria="A.6",
                tipo="preventivo",
                objetivo="Establecer obligaciones de seguridad",
                ejemplo_factoring="Clausulas de confidencialidad en contratos de factoring",
                ejemplo_confirming="Acuerdos de confidencialidad en confirming",
                responsable="RRHH",
                evidencia=["Contratos laborales", "Acuerdos de confidencialidad"],
                normas_relacionadas=["GDPR", "LOC"],
            ),
            # A.7 Controles Físicos (2 controles)
            Control(
                codigo="A.7.1",
                titulo="Perímetro de seguridad",
                descripcion="Definir y usar areas de seguridad",
                categoria="A.7",
                tipo="preventivo",
                objetivo="Proteger areas criticas",
                ejemplo_factoring="Zona segura para documentacion de cartera",
                ejemplo_confirming="Area segura para procesamiento de pagos",
                responsable="Seguridad",
                evidencia=["Planos de seguridad", "Control de acceso"],
                normas_relacionadas=[],
            ),
            Control(
                codigo="A.7.2",
                titulo="Entradas físicas",
                descripcion="Controlar acceso fisico a equipos y areas",
                categoria="A.7",
                tipo="preventivo",
                objetivo="Prevenir acceso no autorizado",
                ejemplo_factoring="Control de acceso a centro de datos de factoring",
                ejemplo_confirming="Control de acceso a sala de servidores de pagos",
                responsable="Seguridad",
                evidencia=["Registro de accesos", "Sistemas de control"],
                normas_relacionadas=[],
            ),
            # A.8 Controles Tecnológicos (13 controles)
            Control(
                codigo="A.8.1",
                titulo="Responsabilidad de usuario",
                descripcion="Asignar responsabilidades a usuarios",
                categoria="A.8",
                tipo="preventivo",
                objetivo="Asegurar uso correcto de recursos",
                ejemplo_factoring="Politica de uso para sistema de factoring",
                ejemplo_confirming="Politica de uso para sistema de pagos",
                responsable="IT",
                evidencia=["Politica de uso", "Aceptacion de usuario"],
                normas_relacionadas=[],
            ),
            Control(
                codigo="A.8.2",
                titulo="Información de los usuarios",
                descripcion="Gestionar Ciclo de vida de informacion de usuarios",
                categoria="A.8",
                tipo="preventivo",
                objetivo="Proteger datos de usuarios",
                ejemplo_factoring="Gestion de datos de clientes de factoring",
                ejemplo_confirming="Gestion de datos de proveedores",
                responsable="IT/DPO",
                evidencia=["Procedimiento de gestion", "Registros"],
                normas_relacionadas=["GDPR", "LGPD"],
            ),
            Control(
                codigo="A.8.3",
                titulo="Control de acceso a la información",
                descripcion="Limitar acceso segun necesidad de conocer",
                categoria="A.8",
                tipo="preventivo",
                objetivo="Prevenir acceso no autorizado",
                ejemplo_factoring="Control de acceso a datos de cartera",
                ejemplo_confirming="Control de acceso a informacion de proveedores",
                responsable="IT",
                evidencia=["Matriz de accesos", "Procedimientos"],
                normas_relacionadas=["ISO27001"],
            ),
            Control(
                codigo="A.8.4",
                titulo="Acceso a código fuente",
                descripcion="Controlar acceso a codigo fuente",
                categoria="A.8",
                tipo="preventivo",
                objetivo="Prevenir modificaciones no autorizadas",
                ejemplo_factoring="Control de versionado de sistemas de factoring",
                ejemplo_confirming="Control de acceso a codigo de pagos",
                responsable="Desarrollo",
                evidencia=["Repositorio seguro", "Bitacoras"],
                normas_relacionadas=["OWASP"],
            ),
            Control(
                codigo="A.8.5",
                titulo="Secure authentication technologies",
                descripcion="Implementar tecnologias de autenticacion segura",
                categoria="A.8",
                tipo="preventivo",
                objetivo="Autenticacion robusta de usuarios",
                ejemplo_factoring="MFA para acceso a sistema de factoring",
                ejemplo_confirming="Autenticacion fuerte para portal de pagos",
                responsable="IT",
                evidencia=["Configuracion MFA", "Politicas de autenticacion"],
                normas_relacionadas=["PSD2", "SCA"],
            ),
            Control(
                codigo="A.8.6",
                titulo="Capacidad de recursos",
                descripcion="Monitorear y ajustar capacidad",
                categoria="A.8",
                tipo="detectivo",
                objetivo="Asegurar disponibilidad",
                ejemplo_factoring="Monitoreo de capacidad de sistema de factoring",
                ejemplo_confirming="Monitoreo de capacidad de procesamiento de pagos",
                responsable="IT",
                evidencia=["Reportes de capacidad", "Alertas"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.8.7",
                titulo="Protección contra malware",
                descripcion="Implementar controles contra malware",
                categoria="A.8",
                tipo="preventivo",
                objetivo="Prevenir infections de malware",
                ejemplo_factoring="Antivirus en estaciones de factoring",
                ejemplo_confirming="Proteccion en servidores de pagos",
                responsable="IT",
                evidencia=["Antivirus instalado", "Actualizaciones"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.8.8",
                titulo="Gestión de vulnerabilidades técnicas",
                descripcion="Gestionar vulnerabilidades tecnicas",
                categoria="A.8",
                tipo="detectivo",
                objetivo="Reducir superficie de ataque",
                ejemplo_factoring="Escaneo de vulnerabilidades en sistemas de factoring",
                ejemplo_confirming="Gestion de parches en sistemas de pago",
                responsable="IT",
                evidencia=["Reportes de vulnerabilidades", "Plan de parches"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.8.9",
                titulo="Configuración",
                descripcion="Establecer y mantener configuraciones seguras",
                categoria="A.8",
                tipo="preventivo",
                objetivo="Hardening de sistemas",
                ejemplo_factoring="Hardening de servidores de factoring",
                ejemplo_confirming="Configuracion segura de sistemas de pago",
                responsable="IT",
                evidencia=["Lineas base de configuracion", "Auditorias"],
                normas_relacionadas=["CIS", "NIST"],
            ),
            Control(
                codigo="A.8.10",
                titulo="Eliminación de información",
                descripcion="Eliminar informacion de forma segura",
                categoria="A.8",
                tipo="correctivo",
                objetivo="Prevenir divulgacion de informacion",
                ejemplo_factoring="Eliminacion segura de datos de clientes",
                ejemplo_confirming="Destruccion de informacion de proveedores",
                responsable="IT",
                evidencia=["Politica de eliminacion", "Certificados de destruccion"],
                normas_relacionadas=["GDPR"],
            ),
            Control(
                codigo="A.8.11",
                titulo="Enmascaramiento de datos",
                descripcion="Aplicar enmascaramiento de datos",
                categoria="A.8",
                tipo="preventivo",
                objetivo="Proteger datos sensibles",
                ejemplo_factoring="Mascarao de datos financieros en pantallas",
                ejemplo_confirming="Tokenizacion de datos de cuentas",
                responsable="Desarrollo",
                evidencia=["Mascarao implementado", "Politicas"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.8.12",
                titulo="Prevención de fuga de datos",
                descripcion="Prevenir fuga de informacion",
                categoria="A.8",
                tipo="detectivo",
                objetivo="Detectar intentos de fuga",
                ejemplo_factoring="DLP para datos de cartera",
                ejemplo_confirming="DLP para informacion de pagos",
                responsable="IT",
                evidencia=["Solucion DLP", "Politicas"],
                normas_relacionadas=["GDPR"],
            ),
            Control(
                codigo="A.8.13",
                titulo="Copias de seguridad",
                descripcion="Mantener copias de seguridad",
                categoria="A.8",
                tipo="preventivo",
                objetivo="Asegurar recuperacion",
                ejemplo_factoring="Backup de base de datos de factoring",
                ejemplo_confirming="Backup de sistema de pagos",
                responsable="IT",
                evidencia=["Politica de backup", "Pruebas de restauracion"],
                normas_relacionadas=["PCI-DSS"],
            ),
            # A.9 Controles de Acceso (9 controles)
            Control(
                codigo="A.9.1",
                titulo="Política de control de acceso",
                descripcion="Definir politica de control de acceso",
                categoria="A.9",
                tipo="preventivo",
                objetivo="Marco para control de acceso",
                ejemplo_factoring="Politica de acceso para sistema de factoring",
                ejemplo_confirming="Politica de acceso para sistema de pagos",
                responsable="CISO",
                evidencia=["Politica de control de acceso", "Aprobacion"],
                normas_relacionadas=[],
            ),
            Control(
                codigo="A.9.2",
                titulo="Gestión de acceso",
                descripcion="Proceso de registro y baja de usuarios",
                categoria="A.9",
                tipo="preventivo",
                objetivo="Controlar acceso de usuarios",
                ejemplo_factoring="Procedimiento de alta/baja de usuarios factoring",
                ejemplo_confirming="Gestion de accesos al sistema de pagos",
                responsable="IT",
                evidencia=["Procedimiento de accesos", "Registros"],
                normas_relacionadas=[],
            ),
            Control(
                codigo="A.9.3",
                titulo="Gestión de derechos de acceso",
                descripcion="Asignar y revocar derechos de acceso",
                categoria="A.9",
                tipo="preventivo",
                objetivo="Controlar privilegios",
                ejemplo_factoring="Revision de accesos trimestral de factoring",
                ejemplo_confirming="Revision de accesos de confirming",
                responsable="IT",
                evidencia=["Matriz de roles", "Registros de cambios"],
                normas_relacionadas=[],
            ),
            Control(
                codigo="A.9.4",
                titulo="Uso del sistema",
                descripcion="Controlar acceso a sistemas y datos",
                categoria="A.9",
                tipo="preventivo",
                objetivo="Asegurar uso autorizado",
                ejemplo_factoring="Control de acceso a datos de clientes factoring",
                ejemplo_confirming="Control de acceso a datos de proveedores",
                responsable="IT",
                evidencia=["Controles tecnicos", "Monitoreo"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.9.5",
                titulo="Seguridad de credenciales",
                descripcion="Gestionar seguridad de contraseñas",
                categoria="A.9",
                tipo="preventivo",
                objetivo="Proteger credenciales",
                ejemplo_factoring="Politica de contrasenas para factoring",
                ejemplo_confirming="Politica de contrasenas para pagos",
                responsable="IT",
                evidencia=["Politica de contrasenas", "Configuracion AD"],
                normas_relacionadas=["NIST"],
            ),
            Control(
                codigo="A.9.6",
                titulo="Derechos de acceso del sistema",
                descripcion="Controlar acceso privilegiado",
                categoria="A.9",
                tipo="preventivo",
                objetivo="Limitar acceso privilegiado",
                ejemplo_factoring="Control de acceso admin a sistemas factoring",
                ejemplo_confirming="Control de acceso admin a sistemas de pago",
                responsable="IT",
                evidencia=["Cuentas privilegiadas", "Monitoreo"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.9.7",
                titulo="Acceso remoto",
                descripcion="Controlar acceso remoto",
                categoria="A.9",
                tipo="preventivo",
                objetivo="Proteger acceso remoto",
                ejemplo_factoring="VPN para acceso remoto a factoring",
                ejemplo_confirming="Acceso remoto seguro a sistemas de pago",
                responsable="IT",
                evidencia=["VPN configurada", "Politicas de acceso remoto"],
                normas_relacionadas=[],
            ),
            Control(
                codigo="A.9.8",
                titulo="Registro de eventos",
                descripcion="Registrar eventos de acceso",
                categoria="A.9",
                tipo="detectivo",
                objetivo="Auditar accesos",
                ejemplo_factoring="Logs de acceso a sistema de factoring",
                ejemplo_confirming="Logs de acceso a sistema de pagos",
                responsable="IT",
                evidencia=["Logs almacenados", "Revision de logs"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.9.9",
                titulo="Bloqueo de pantalla",
                descripcion="Bloquear sesiones inactivas",
                categoria="A.9",
                tipo="preventivo",
                objetivo="Prevenir acceso no autorizado",
                ejemplo_factoring="Bloqueo automatico en terminales de factoring",
                ejemplo_confirming="Bloqueo automatico en estaciones de pago",
                responsable="IT",
                evidencia=["Politica de bloqueo", "Configuracion"],
                normas_relacionadas=[],
            ),
            # A.10 Criptografía (2 controles)
            Control(
                codigo="A.10.1",
                titulo="Controles criptográficos",
                descripcion="Politica y procedimientos de criptografia",
                categoria="A.10",
                tipo="preventivo",
                objetivo="Proteger informacion",
                ejemplo_factoring="Cifrado de datos de cartera cedida",
                ejemplo_confirming="Cifrado de datos de transacciones",
                responsable="IT",
                evidencia=["Politica de cifrado", "Certificados"],
                normas_relacionadas=["PCI-DSS", "GDPR"],
            ),
            Control(
                codigo="A.10.2",
                titulo="Gestión de claves",
                descripcion="Gestionar claves criptograficas",
                categoria="A.10",
                tipo="preventivo",
                objetivo="Proteger claves",
                ejemplo_factoring="Rotacion de claves de cifrado factoring",
                ejemplo_confirming="Gestion de claves HSM para pagos",
                responsable="IT",
                evidencia=["Politica de claves", "Procedimientos"],
                normas_relacionadas=["PCI-DSS"],
            ),
            # A.11 Operaciones de Seguridad (14 controles)
            Control(
                codigo="A.11.1",
                titulo="Responsabilidades y procedimientos",
                descripcion="Definir responsabilidades de operacion",
                categoria="A.11",
                tipo="preventivo",
                objetivo="Asegurar operaciones seguras",
                ejemplo_factoring="Procedimientos de operacion de factoring",
                ejemplo_confirming="Procedimientos de procesamiento de pagos",
                responsable="Operaciones",
                evidencia=["Procedimientos documentados", "Manuales"],
                normas_relacionadas=[],
            ),
            Control(
                codigo="A.11.2",
                titulo="Segregación de duties",
                descripcion="Separar funciones de operacion",
                categoria="A.11",
                tipo="preventivo",
                objetivo="Prevenir fraude",
                ejemplo_factoring="Separacion entre aprobacion y registro factoring",
                ejemplo_confirming="Separacion entre ingreso y aprobacion de pagos",
                responsable="Operaciones",
                evidencia=["Matriz de segregacion", "Procedimientos"],
                normas_relacionadas=["SOX"],
            ),
            Control(
                codigo="A.11.3",
                titulo="Segregación de redes",
                descripcion="Separar redes por funciones",
                categoria="A.11",
                tipo="preventivo",
                objetivo="Limitar propagacion de ataques",
                ejemplo_factoring="Segmentacion de red de factoring",
                ejemplo_confirming="Segmentacion de red de pagos",
                responsable="Redes",
                evidencia=["Diagrama de red", "Politicas de segmentacion"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.11.4",
                titulo="Gestión de vulnerabilidades",
                descripcion="Gestionar vulnerabilidades tecnicas",
                categoria="A.11",
                tipo="detectivo",
                objetivo="Reducir vulnerabilidades",
                ejemplo_factoring="Escaneo de vulnerabilidades factoring",
                ejemplo_confirming="Gestion de parches de pagos",
                responsable="IT",
                evidencia=["Reportes VA", "Plan de remediacion"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.11.5",
                titulo="Protección contra malware",
                descripcion="Controles contra malware",
                categoria="A.11",
                tipo="preventivo",
                objetivo="Prevenir malware",
                ejemplo_factoring="Antivirus y anti-malware factoring",
                ejemplo_confirming="Proteccion endpoint en sistemas de pago",
                responsable="IT",
                evidencia=["Solucion antimalware", "Actualizaciones"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.11.6",
                titulo="Gestión de medios",
                descripcion="Controlar medios extraibles",
                categoria="A.11",
                tipo="preventivo",
                objetivo="Prevenir fuga de datos",
                ejemplo_factoring="Control de USB en area de factoring",
                ejemplo_confirming="Control de medios en procesamiento de pagos",
                responsable="IT",
                evidencia=["Politica de medios", "Controles"],
                normas_relacionadas=[],
            ),
            Control(
                codigo="A.11.7",
                titulo="Procedimientos de operación",
                descripcion="Documentar procedimientos operativos",
                categoria="A.11",
                tipo="preventivo",
                objetivo="Consistencia operativa",
                ejemplo_factoring="Manual de operacion de factoring",
                ejemplo_confirming="Procedimientos de procesamiento de pagos",
                responsable="Operaciones",
                evidencia=["Manuales operativos", "Checklists"],
                normas_relacionadas=[],
            ),
            Control(
                codigo="A.11.8",
                titulo="Gestión de cambios",
                descripcion="Controlar cambios en sistemas",
                categoria="A.11",
                tipo="preventivo",
                objetivo="Asegurar cambios controlados",
                ejemplo_factoring="Procedimiento de cambios en factoring",
                ejemplo_confirming="Gestion de cambios en sistemas de pago",
                responsable="IT",
                evidencia=["Procedimiento de cambios", "Aprobaciones"],
                normas_relacionadas=["ITIL"],
            ),
            Control(
                codigo="A.11.9",
                titulo="Gestión de capacidad",
                descripcion="Monitorear uso de recursos",
                categoria="A.11",
                tipo="detectivo",
                objetivo="Asegurar capacidad suficiente",
                ejemplo_factoring="Monitoreo de capacidad factoring",
                ejemplo_confirming="Monitoreo de capacidad de procesamiento",
                responsable="IT",
                evidencia=["Reportes de capacidad", "Alertas"],
                normas_relacionadas=[],
            ),
            Control(
                codigo="A.11.10",
                titulo="Software de producción",
                descripcion="Separar entornos de desarrollo y produccion",
                categoria="A.11",
                tipo="preventivo",
                objetivo="Proteger entornos de produccion",
                ejemplo_factoring="Separacion de entornos factoring",
                ejemplo_confirming="Entornos separados para pagos",
                responsable="Desarrollo",
                evidencia=["Politica de entornos", "Control de cambios"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.11.11",
                titulo="Protección de sistemas",
                descripcion="Proteger sistemas contra amenazas",
                categoria="A.11",
                tipo="preventivo",
                objetivo="Asegurar integridad",
                ejemplo_factoring="Hardening de servidores factoring",
                ejemplo_confirming="Proteccion de sistemas de pago",
                responsable="IT",
                evidencia=["Lineas base", "Auditorias"],
                normas_relacionadas=["CIS", "NIST"],
            ),
            Control(
                codigo="A.11.12",
                titulo="Desarrollo seguro",
                descripcion="Desarrollar software de forma segura",
                categoria="A.11",
                tipo="preventivo",
                objetivo="Reducir vulnerabilidades",
                ejemplo_factoring="Secure coding para sistemas de factoring",
                ejemplo_confirming="Desarrollo seguro para aplicaciones de pago",
                responsable="Desarrollo",
                evidencia=["Estandares de codificacion", "Code review"],
                normas_relacionadas=["OWASP"],
            ),
            Control(
                codigo="A.11.13",
                titulo="Pruebas de seguridad",
                descripcion="Realizar pruebas de seguridad",
                categoria="A.11",
                tipo="detectivo",
                objetivo="Validar controles",
                ejemplo_factoring="Pruebas de penetracion en factoring",
                ejemplo_confirming="Penetration testing en sistemas de pago",
                responsable="Seguridad",
                evidencia=["Reportes de pruebas", "Remediacion"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.11.14",
                titulo="Aceptación de sistemas",
                descripcion="Criterios de aceptacion de sistemas",
                categoria="A.11",
                tipo="preventivo",
                objetivo="Asegurar calidad",
                ejemplo_factoring="Criterios de aceptacion factoring",
                ejemplo_confirming="Aceptacion de nuevos modulos de pago",
                responsable="IT",
                evidencia=["Criterios de aceptacion", "Pruebas"],
                normas_relacionadas=[],
            ),
            # A.12 Seguridad de las Comunicaciones (10 controles)
            Control(
                codigo="A.12.1",
                titulo="Gestión de red",
                descripcion="Gestionar redes de forma segura",
                categoria="A.12",
                tipo="preventivo",
                objetivo="Proteger comunicaciones",
                ejemplo_factoring="Gestion de red de operaciones factoring",
                ejemplo_confirming="Gestion de red de sistemas de pago",
                responsable="Redes",
                evidencia=["Politica de red", "Documentacion"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.12.2",
                titulo="Transferencia de información",
                descripcion="Proteger transferencia de informacion",
                categoria="A.12",
                tipo="preventivo",
                objetivo="Cifrar transferencias",
                ejemplo_factoring="TLS para transferencia de datos factoring",
                ejemplo_confirming="Canal seguro para transacciones de pago",
                responsable="IT",
                evidencia=["TLS implementado", "SFTP"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.12.3",
                titulo="Mensajería electrónica",
                descripcion="Proteger comunicaciones por email",
                categoria="A.12",
                tipo="preventivo",
                objetivo="Asegurar confidencialidad",
                ejemplo_factoring="Cifrado de email con datos de clientes",
                ejemplo_confirming="Politicas de email para pagos",
                responsable="IT",
                evidencia=["Cifrado email", "DLP"],
                normas_relacionadas=["GDPR"],
            ),
            Control(
                codigo="A.12.4",
                titulo="Acuerdos de confidencialidad",
                descripcion="Acuerdos de NDA",
                categoria="A.12",
                tipo="preventivo",
                objetivo="Proteger informacion",
                ejemplo_factoring="NDA con empleados factoring",
                ejemplo_confirming="NDA con proveedores de servicios de pago",
                responsable="Legal",
                evidencia=["Plantillas de NDA", "Registros"],
                normas_relacionadas=["GDPR"],
            ),
            Control(
                codigo="A.12.5",
                titulo="Desarrollo de aplicaciones",
                descripcion="Desarrollar aplicaciones seguras",
                categoria="A.12",
                tipo="preventivo",
                objetivo="Reducir vulnerabilidades",
                ejemplo_factoring="Secure SDLC para factoring",
                ejemplo_confirming="Desarrollo seguro de app de pagos",
                responsable="Desarrollo",
                evidencia=["SDL implementada", "SAST"],
                normas_relacionadas=["OWASP"],
            ),
            Control(
                codigo="A.12.6",
                titulo="Gestión de vulnerabilidades técnicas",
                descripcion="Gestionar vulnerabilidades en aplicaciones",
                categoria="A.12",
                tipo="detectivo",
                objetivo="Remediar vulnerabilidades",
                ejemplo_factoring="Escaneo SAST factoring",
                ejemplo_confirming="Analisis de codigo de pagos",
                responsable="Desarrollo",
                evidencia=["Reportes DAST/SAST", "Remediacion"],
                normas_relacionadas=["OWASP"],
            ),
            Control(
                codigo="A.12.7",
                titulo="Seguridad de la configuración",
                descripcion="Configuraciones seguras de sistemas",
                categoria="A.12",
                tipo="preventivo",
                objetivo="Hardening",
                ejemplo_factoring="Hardening de servidores factoring",
                ejemplo_confirming="Configuracion segura de POS",
                responsable="IT",
                evidencia=["Lineas base", "Auditorias"],
                normas_relacionadas=["CIS"],
            ),
            Control(
                codigo="A.12.8",
                titulo="Eliminación de información",
                descripcion="Eliminar informacion de forma segura",
                categoria="A.12",
                tipo="correctivo",
                objetivo="Prevenir fuga",
                ejemplo_factoring="Eliminacion segura de datos de clientes",
                ejemplo_confirming="Destruccion de datos de transacciones",
                responsable="IT",
                evidencia=["Procedimientos de eliminacion", "Certificados"],
                normas_relacionadas=["GDPR"],
            ),
            Control(
                codigo="A.12.9",
                titulo="Protección de datos en uso",
                descripcion="Proteger datos mientras se procesan",
                categoria="A.12",
                tipo="preventivo",
                objetivo="Confidencialidad en procesamiento",
                ejemplo_factoring="Procesamiento seguro de datos de cartera",
                ejemplo_confirming="Procesamiento seguro de transacciones",
                responsable="Desarrollo",
                evidencia=["Controles de memoria segura", "Tokenizacion"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.12.10",
                titulo="Monitoreo de actividades",
                descripcion="Monitorear actividades de usuarios y sistemas",
                categoria="A.12",
                tipo="detectivo",
                objetivo="Detectar anomalias",
                ejemplo_factoring="Monitoreo de operaciones de factoring",
                ejemplo_confirming="Monitoreo de transacciones de pago",
                responsable="SOC",
                evidencia=["SIEM configurado", "Alertas"],
                normas_relacionadas=["PCI-DSS"],
            ),
            # A.13 Adquisición y Desarrollo (7 controles)
            Control(
                codigo="A.13.1",
                titulo="Requisitos de seguridad",
                descripcion="Incluir requisitos de seguridad",
                categoria="A.13",
                tipo="preventivo",
                objetivo="Asegurar seguridad en adquisiciones",
                ejemplo_factoring="Requisitos de seguridad para sistemas de factoring",
                ejemplo_confirming="Requisitos de seguridad para plataforma de pagos",
                responsable="CISO",
                evidencia=["Especificaciones de seguridad", "Contratos"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.13.2",
                titulo="Desarrollo seguro",
                descripcion="Desarrollar software de forma segura",
                categoria="A.13",
                tipo="preventivo",
                objetivo="Reducir vulnerabilidades",
                ejemplo_factoring="Metodologia de desarrollo factoring",
                ejemplo_confirming="Secure SDLC para aplicaciones de pago",
                responsable="Desarrollo",
                evidencia=["Politica de seguridad", "Code review"],
                normas_relacionadas=["OWASP"],
            ),
            Control(
                codigo="A.13.3",
                titulo="Control de versiones",
                descripcion="Controlar cambios en configuracion",
                categoria="A.13",
                tipo="preventivo",
                objetivo="Trazabilidad de cambios",
                ejemplo_factoring="Versionado de configuracion factoring",
                ejemplo_confirming="Control de versiones de aplicaciones de pago",
                responsable="Desarrollo",
                evidencia=["Git configurado", "Politicas de branching"],
                normas_relacionadas=["ITIL"],
            ),
            Control(
                codigo="A.13.4",
                titulo="Separación de entornos",
                descripcion="Separar desarrollo, prueba y produccion",
                categoria="A.13",
                tipo="preventivo",
                objetivo="Proteger produccion",
                ejemplo_factoring="Entornos separados factoring",
                ejemplo_confirming="Entornos aislados para pagos",
                responsable="Desarrollo",
                evidencia=["Politica de entornos", "Control de acceso"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.13.5",
                titulo="Contraseñas embebidas",
                descripcion="No incluir contrasenas en codigo",
                categoria="A.13",
                tipo="preventivo",
                objetivo="Proteger credenciales",
                ejemplo_factoring="Gestor de secretos para factoring",
                ejemplo_confirming="Vault para credenciales de pago",
                responsable="Desarrollo",
                evidencia=["HashiCorp Vault", "Politica de secretos"],
                normas_relacionadas=["OWASP"],
            ),
            Control(
                codigo="A.13.6",
                titulo="Evaluación de seguridad",
                descripcion="Evaluar seguridad de desarrollo",
                categoria="A.13",
                tipo="detectivo",
                objetivo="Validar seguridad",
                ejemplo_factoring="Revisiones de seguridad factoring",
                ejemplo_confirming="Penetration testing de aplicaciones de pago",
                responsable="Seguridad",
                evidencia=["Reportes de evaluacion", "Remediacion"],
                normas_relacionadas=["OWASP"],
            ),
            Control(
                codigo="A.13.7",
                titulo="Outsourcing del desarrollo",
                descripcion="Controlar desarrollo tercerizado",
                categoria="A.13",
                tipo="preventivo",
                objetivo="asegurar seguridad en terceros",
                ejemplo_factoring="Controles para desarrollo offshore factoring",
                ejemplo_confirming="Auditoria a proveedores de desarrollo de pagos",
                responsable="CISO",
                evidencia=["Contratos", "Auditorias"],
                normas_relacionadas=["PCI-DSS"],
            ),
            # A.14 Relación con Proveedores (5 controles)
            Control(
                codigo="A.14.1",
                titulo="Información del proveedor",
                descripcion="Identificar y gestionar riesgos de proveedores",
                categoria="A.14",
                tipo="preventivo",
                objetivo="asegurar seguridad de terceros",
                ejemplo_factoring="Evaluacion de proveedores de factoring",
                ejemplo_confirming="Evaluacion de procesadores de pago",
                responsable="Proveedores",
                evidencia=["Registro de proveedores", "Evaluaciones"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.14.2",
                titulo="Requisitos de seguridad",
                descripcion="Acordar requisitos de seguridad con proveedores",
                categoria="A.14",
                tipo="preventivo",
                objetivo="formalizar obligaciones",
                ejemplo_factoring="Clausulas de seguridad en contratos factoring",
                ejemplo_confirming="Requisitos de seguridad con pasarelas de pago",
                responsable="Legal",
                evidencia=["Contratos con clausulas", "SLAs"],
                normas_relacionadas=["GDPR"],
            ),
            Control(
                codigo="A.14.3",
                titulo="Evaluación de proveedores",
                descripcion="Evaluar y monitorear proveedores",
                categoria="A.14",
                tipo="detectivo",
                objetivo="asegurar cumplimiento",
                ejemplo_factoring="Evaluacion anual de proveedores factoring",
                ejemplo_confirming="Evaluacion de proveedores de servicios de pago",
                responsable="Proveedores",
                evidencia=["Reportes de evaluacion", "Acciones"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.14.4",
                titulo="Gestión de cambios",
                descripcion="Gestionar cambios en proveedores",
                categoria="A.14",
                tipo="preventivo",
                objetivo="Mantener seguridad",
                ejemplo_factoring="Cambios en proveedores de factoring",
                ejemplo_confirming="Gestion de cambios con proveedores de pago",
                responsable="Proveedores",
                evidencia=["Procedimiento de cambios", "Evaluacion de impacto"],
                normas_relacionadas=[],
            ),
            Control(
                codigo="A.14.5",
                titulo="Terminación de relación",
                descripcion="Gestionar terminacion de proveedores",
                categoria="A.14",
                tipo="correctivo",
                objetivo="Proteger informacion",
                ejemplo_factoring="Procedimiento de terminacion factoring",
                ejemplo_confirming="Devolucion de datos al terminar relacion de pago",
                responsable="Legal",
                evidencia=["Procedimiento de terminacion", "Verificacion"],
                normas_relacionadas=["GDPR"],
            ),
            # A.15 Gestión de Incidentes (9 controles)
            Control(
                codigo="A.15.1",
                titulo="Gestión de incidentes",
                descripcion="Establecer gestion de incidentes",
                categoria="A.15",
                tipo="correctivo",
                objetivo="Responder efectivamente",
                ejemplo_factoring="Procedimiento de incidentes de factoring",
                ejemplo_confirming="Plan de respuesta a incidentes de pago",
                responsable="CISO",
                evidencia=["Procedimiento documentado", "Equipo CSIRT"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.15.2",
                titulo="Notificación de incidentes",
                descripcion="Reportar incidentes de seguridad",
                categoria="A.15",
                tipo="correctivo",
                objetivo="Comunicar rapidamente",
                ejemplo_factoring="Notificacion de incidentes factoring",
                ejemplo_confirming="Notificacion de brechas de datos de pago",
                responsable="CISO",
                evidencia=["Canal de notificacion", "Plantillas"],
                normas_relacionadas=["GDPR", "PCI-DSS"],
            ),
            Control(
                codigo="A.15.3",
                titulo="Evaluación de incidentes",
                descripcion="Evaluar y clasificar incidentes",
                categoria="A.15",
                tipo="detectivo",
                objetivo="Priorizar respuesta",
                ejemplo_factoring="Clasificacion de incidentes factoring",
                ejemplo_confirming="Triage de incidentes de pago",
                responsable="SOC",
                evidencia=["Criterios de clasificacion", "Escalamiento"],
                normas_relacionadas=[],
            ),
            Control(
                codigo="A.15.4",
                titulo="Respuesta a incidentes",
                descripcion="Responder a incidentes",
                categoria="A.15",
                tipo="correctivo",
                objetivo="Contener y resolver",
                ejemplo_factoring="Playbooks de respuesta factoring",
                ejemplo_confirming="Procedimientos de respuesta a fraude",
                responsable="SOC",
                evidencia=["Playbooks", "Ejercicios"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.15.5",
                titulo="Análisis de incidentes",
                descripcion="Analizar causa raiz de incidentes",
                categoria="A.15",
                tipo="correctivo",
                objetivo="Prevenir recurrencia",
                ejemplo_factoring="Analisis post-incidente factoring",
                ejemplo_confirming="Lecciones aprendidas de incidentes de pago",
                responsable="CISO",
                evidencia=["Informes de analisis", "Acciones correctivas"],
                normas_relacionadas=[],
            ),
            Control(
                codigo="A.15.6",
                titulo="Recuperación de incidentes",
                descripcion="Recuperar de incidentes",
                categoria="A.15",
                tipo="correctivo",
                objetivo="Restaurar servicios",
                ejemplo_factoring="Recuperacion de sistemas de factoring",
                ejemplo_confirming="Recuperacion de servicios de pago",
                responsable="IT",
                evidencia=["Plan de recuperacion", "Pruebas"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.15.7",
                titulo="Comunicación de incidentes",
                descripcion="Comunicar incidentes externamente",
                categoria="A.15",
                tipo="correctivo",
                objetivo="Stakeholders informados",
                ejemplo_factoring="Comunicacion a clientes factoring",
                ejemplo_confirming="Notificacion a reguladores de pago",
                responsable="Comunicacion",
                evidencia=["Plantillas de comunicacion", "Contactos"],
                normas_relacionadas=["GDPR"],
            ),
            Control(
                codigo="A.15.8",
                titulo="Recopilación de evidencias",
                descripcion="Recopilar y preservar evidencias",
                categoria="A.15",
                tipo="correctivo",
                objetivo="Soportar investigacion",
                ejemplo_factoring="Recopilacion de evidencias factoring",
                ejemplo_confirming="Cadena de custodia para fraude",
                responsable="Legal",
                evidencia=["Procedimiento de evidencias", "Herramientas"],
                normas_relacionadas=[],
            ),
            Control(
                codigo="A.15.9",
                titulo="Lecciones aprendidas",
                descripcion="Documentar lecciones aprendidas",
                categoria="A.15",
                tipo="preventivo",
                objetivo="Mejora continua",
                ejemplo_factoring="Revision post-incidente factoring",
                ejemplo_confirming="Mejoras tras incidentes de pago",
                responsable="CISO",
                evidencia=["Informes de lecciones", "Actualizaciones"],
                normas_relacionadas=[],
            ),
            # A.16 Continuidad del Negocio (4 controles)
            Control(
                codigo="A.16.1",
                titulo="Continuidad de la información",
                descripcion="Asegurar continuidad de seguridad",
                categoria="A.16",
                tipo="preventivo",
                objetivo="mantener seguridad en emergencias",
                ejemplo_factoring="Contingencia para operaciones de factoring",
                ejemplo_confirming="Plan de continuidad para pagos",
                responsable="CISO",
                evidencia=["BCP de seguridad", "PRP"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.16.2",
                titulo="Sitios alternativos",
                descripcion="Disponer de sitios alternativos",
                categoria="A.16",
                tipo="preventivo",
                objetivo="asegurar disponibilidad",
                ejemplo_factoring="Sitio backup para factoring",
                ejemplo_confirming="Centro de datos alternativo para pagos",
                responsable="IT",
                evidencia=["Sitio alternativo configurado", "Pruebas"],
                normas_relacionadas=["PCI-DSS"],
            ),
            Control(
                codigo="A.16.3",
                titulo="Ejercicios de continuidad",
                descripcion="Probar planes de continuidad",
                categoria="A.16",
                tipo="detectivo",
                objetivo="Validar eficacia",
                ejemplo_factoring="Simulacros de continuidad factoring",
                ejemplo_confirming="Drills de continuidad de pagos",
                responsable="CISO",
                evidencia=["Reportes de ejercicios", "Acciones"],
                normas_relacionadas=[],
            ),
            Control(
                codigo="A.16.4",
                titulo="Revisión de continuidad",
                descripcion="Revisar planes de continuidad",
                categoria="A.16",
                tipo="preventivo",
                objetivo="Mantener actualizados",
                ejemplo_factoring="Revision anual del BCP factoring",
                ejemplo_confirming="Actualizacion de plan de pagos",
                responsable="CISO",
                evidencia=["Actas de revision", "Actualizaciones"],
                normas_relacionadas=[],
            ),
            # A.17 Cumplimiento (2 controles)
            Control(
                codigo="A.17.1",
                titulo="Cumplimiento legal",
                descripcion="Cumplir requisitos legales",
                categoria="A.17",
                tipo="preventivo",
                objetivo="Evitar sanciones",
                ejemplo_factoring="Cumplimiento regulatorio financiero",
                ejemplo_confirming="Cumplimiento de normas de pago",
                responsable="Legal",
                evidencia=["Mapeo de requisitos", "Registros"],
                normas_relacionadas=["LOC", "Basilea"],
            ),
            Control(
                codigo="A.17.2",
                titulo="Revisión de cumplimiento",
                descripcion="Verificar cumplimiento de politicas",
                categoria="A.17",
                tipo="detectivo",
                objetivo="asegurar adherencia",
                ejemplo_factoring="Auditoria de cumplimiento factoring",
                ejemplo_confirming="Verificacion de cumplimiento de pagos",
                responsable="Cumplimiento",
                evidencia=["Informes de auditoria", "Acciones"],
                normas_relacionadas=["ISO27001"],
            ),
        ]

    @staticmethod
    def get_template_json() -> str:
        import json

        controls = ControlesISO27001.get_all()
        return json.dumps([c.to_dict() for c in controls], indent=2, ensure_ascii=False)

    @staticmethod
    def get_controls_by_category() -> Dict:
        controls = ControlesISO27001.get_all()
        by_category = {}
        for c in controls:
            if c.categoria not in by_category:
                by_category[c.categoria] = []
            by_category[c.categoria].append(c.to_dict())
        return by_category
